### ISSUE TITLE
Exception reported: Client x is not in game

### ISSUE THREAD

**Issue by rzrhome** [Shivaah/multicfg-deathmatch#5]
can one fix this ?

L 11/03/2019 - 12:39:18: [SM] Exception reported: Client 2 is not in game
L 11/03/2019 - 12:39:18: [SM] Blaming: MultiCFG-DM.smx
L 11/03/2019 - 12:39:18: [SM] Call stack trace:
L 11/03/2019 - 12:39:18: [SM]   [0] IsClientObserver
L 11/03/2019 - 12:39:18: [SM]   [1] Line 239, MultiCFG-DM.sp::PlaySound
L 11/03/2019 - 12:39:18: [SM]   [2] Line 122, MultiCFG-DM.sp::ExecConfig
L 11/03/2019 - 12:39:18: [SM]   [3] Line 66, MultiCFG-DM.sp::Event_RoundStart
L 11/03/2019 - 12:39:37: [SM] Exception reported: Client 4 is not connected
L 11/03/2019 - 12:39:37: [SM] Blaming: MultiCFG-DM.smx
L 11/03/2019 - 12:39:37: [SM] Call stack trace:
L 11/03/2019 - 12:39:37: [SM]   [0] IsFakeClient
L 11/03/2019 - 12:39:37: [SM]   [1] Line 239, MultiCFG-DM.sp::PlaySound
L 11/03/2019 - 12:39:37: [SM]   [2] Line 122, MultiCFG-DM.sp::ExecConfig
L 11/03/2019 - 12:39:37: [SM]   [3] Line 66, MultiCFG-DM.sp::Event_RoundStart

**Comment by Shivaah** [comment]
Sorry but I don't support this plugin anymore, I invite you to go to this repository to report your issue  : https://github.com/Balimbanana/multicfg-deathmatch
